all:
  hosts:
    wtmp:
      ansible_host: 62.84.116.80
      ansible_user: ycuser
      ansible_become: yes
      wireguard_address: "10.8.0.101/24"
      wireguard_allowed_ips: "10.8.0.101/32"
      wireguard_endpoint: 62.84.116.80
    sel-bl09:
      ansible_host: 87.249.37.140
      ansible_user: root
      wireguard_address: "10.8.0.102/24"
      wireguard_allowed_ips: "10.8.0.102/32"
      wireguard_endpoint: 87.249.37.140

  children:
    vpn:
      hosts:
        wtmp:
        sel-bl09:
